### ISSUE TITLE
[Bug]: When I run Aki.server : TypeError: Cannot read properties of undefined (reading 'base')

### ISSUE THREAD

**Issue by Gadjoo** [refringe/CustomRaidTimes#6]
### What happened?

When I start Aki.server, the server does not start and displays the red lines displayed in "server log". 
My file is here 
C:\SPT Tarkov\user\mods\refringe-customraidtimes

Thanks

### SPT Version

3.8.0

### Server Log

```shell
TypeError: Cannot read properties of undefined (reading 'base')
TypeError: Cannot read properties of undefined (reading 'base')
    at LocationProcessor.processLocations (C:\SPT Tarkov\user\mods\refringe-customraidtimes\src\processors\LocationProcessor.ts:48:59)
    at CustomRaidTimes.initializer (C:\SPT Tarkov\user\mods\refringe-customraidtimes\src\customRaidTimes.ts:96:33)
    at CustomRaidTimes.postDBLoad (C:\SPT Tarkov\user\mods\refringe-customraidtimes\src\customRaidTimes.ts:85:14)
    at PostDBModLoader.executeMods (C:\snapshot\project\src\loaders\PostDBModLoader.ts:72:45)
    at PostDBModLoader.onLoad (C:\snapshot\project\src\loaders\PostDBModLoader.ts:26:24)
    at App.load (C:\snapshot\project\src\utils\App.ts:56:26)
TypeError: Cannot read properties of undefined (reading 'base')
TypeError: Cannot read properties of undefined (reading 'base')
    at LocationProcessor.processLocations (C:\SPT Tarkov\user\mods\refringe-customraidtimes\src\processors\LocationProcessor.ts:48:59)
    at CustomRaidTimes.initializer (C:\SPT Tarkov\user\mods\refringe-customraidtimes\src\customRaidTimes.ts:96:33)
    at CustomRaidTimes.postDBLoad (C:\SPT Tarkov\user\mods\refringe-customraidtimes\src\customRaidTimes.ts:85:14)
    at PostDBModLoader.executeMods (C:\snapshot\project\src\loaders\PostDBModLoader.ts:72:45)
    at PostDBModLoader.onLoad (C:\snapshot\project\src\loaders\PostDBModLoader.ts:26:24)
    at App.load (C:\snapshot\project\src\utils\App.ts:56:26)
```

**Comment by refringe** [comment]
Which version of SPT are you running? Can you please update the issue with your full server log?

**Comment by Gadjoo** [comment]
sorry the logs will be in French. I'm playing with version 3.7.6. It seems that this is not compatible. what do I have to do


Commit hash: 40b999d04c68f1f52ab152d163c086a1c50f489b
Build date: 1703675180248
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ SPT-AKI 3.7.6                                                                                                                                                                    │
│ https://discord.sp-tarkov.com                                                                                                                                                    │
│                                                                                                                                                                                  │
│ Ce travail est gratuit                                                                                                                                                           │
│ Si vous avez payé pour utiliser SPT ce n'est pas normal, c'est une ARNAQUE. Par contre attention : payer pour posséder le jeu original EfT est tout à fait normal et obligatoire │
│ tout usage commercial est interdit !!!                                                                                                                                           │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModLoader: Chargement de 2 mods...
le mod Refringe-custom-raid-times  n'est pas compatible avec la version actuelle de SPT-AKI. Des erreurs peuvent survenir - aucun support ne sera fourni !
Mod custom-raid-times version 1.6.0 par Refringe chargé
Mod NLE version 6.1.0 par Revingly chargé
Revingly-NeverLoseEquipment: Active
Serveur: exécution des appels de démarrage...
importation de la base de données...
Importation de la base de données terminée.
TypeError: Cannot read properties of undefined (reading 'base')
TypeError: Cannot read properties of undefined (reading 'base')
    at LocationProcessor.processLocations (C:\SPT Tarkov\user\mods\refringe-customraidtimes\src\processors\LocationProcessor.ts:48:59)
    at CustomRaidTimes.initializer (C:\SPT Tarkov\user\mods\refringe-customraidtimes\src\customRaidTimes.ts:96:33)
    at CustomRaidTimes.postDBLoad (C:\SPT Tarkov\user\mods\refringe-customraidtimes\src\customRaidTimes.ts:85:14)
    at PostDBModLoader.executeMods (C:\snapshot\project\src\loaders\PostDBModLoader.ts:72:45)
    at PostDBModLoader.onLoad (C:\snapshot\project\src\loaders\PostDBModLoader.ts:26:24)
    at App.load (C:\snapshot\project\src\utils\App.ts:56:26)
TypeError: Cannot read properties of undefined (reading 'base')
TypeError: Cannot read properties of undefined (reading 'base')
    at LocationProcessor.processLocations (C:\SPT Tarkov\user\mods\refringe-customraidtimes\src\processors\LocationProcessor.ts:48:59)
    at CustomRaidTimes.initializer (C:\SPT Tarkov\user\mods\refringe-customraidtimes\src\customRaidTimes.ts:96:33)
    at CustomRaidTimes.postDBLoad (C:\SPT Tarkov\user\mods\refringe-customraidtimes\src\customRaidTimes.ts:85:14)
    at PostDBModLoader.executeMods (C:\snapshot\project\src\loaders\PostDBModLoader.ts:72:45)
    at PostDBModLoader.onLoad (C:\snapshot\project\src\loaders\PostDBModLoader.ts:26:24)
    at App.load (C:\snapshot\project\src\utils\App.ts:56:26)

**Comment by refringe** [comment]
You will have to download a version of the mod that is compatiable with SPT v3.7.6. Try this one:  
https://github.com/refringe/CustomRaidTimes/releases/tag/v1.5.0

Please be aware that I do not offer support for running old versions of this mod or old versions of SPT. Thank you!
